### ISSUE TITLE
Data API

### ISSUE THREAD

**Issue by arthurkuahara** [gustavomoers/FinanceDash#1]
Hey there, Gustavo! 

First of all, appreciate the work put into this, looks like a very cool project! 

This 'feature request', per se, is actually about something you've addressed in the README - the data collection project. Your database seems very diverse and complete, so I would greatly appreciate if you'd make it available to the public! The data sources aren't the friendliest to obtain information from through APIs, so it'd be of great help to have a program that can assemble a dataframe out of these many data sources.

I understand you currently feel like it's not ready to be released, so my question is pretty direct : do you plan on releasing it anytime soon? I'm eager to try it out, if you'd be willing to share it!

Once again, I congratulate you on this very interesting project, and would love to hear back.

Best,

Arthur

**Comment by gustavomoers** [comment]
Hi,

sorry for this delayed answer, but I just published it! It still a bit confusing but you can check it out here:
https://github.com/gustavomoers/BrazilianMarketDataAPI

Thank you,
Gustavo
